# Generated by Django 3.2.10 on 2021-12-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=64)),
                ('en_name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lowest.brands')),
                ('current', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current', to='lowest.history')),
                ('highest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='highest', to='lowest.history')),
                ('lowest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lowest', to='lowest.history')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowest.products'),
        ),
    ]
