# Generated by Django 3.2.10 on 2021-12-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lowest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current', to='lowest.history'),
        ),
        migrations.AlterField(
            model_name='products',
            name='highest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest', to='lowest.history'),
        ),
        migrations.AlterField(
            model_name='products',
            name='lowest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lowest', to='lowest.history'),
        ),
    ]
