# Generated by Django 3.2.10 on 2021-12-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowest', '0003_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.BigIntegerField(),
        ),
    ]
